### ISSUE TITLE
UTF-8 decode issue when crawling

### ISSUE THREAD

**Issue by pa-jberanek** [shirosaidev/diskover#18] opened 2018-01-19 11:43 UTC
I installed diskover to hopefully get some insight into a large-ish dataset on an old NetApp filer.

A short way into the crawl diskover stops with a traceback about failing to decode UTF-8:

```
2018-01-19 10:46:11,547 [INFO][diskover] Creating ES index
2018-01-19 10:46:11,796 [INFO][diskover] Adding disk space info to ES index
2018-01-19 10:46:11,804 [INFO][diskover] Starting crawl using 8 threads
Crawling: 100%|████████████████████| 5630/5643 [0h:00m:00s, 36.7 dir/s]Traceback (most recent call last):
  File "diskover.py", line 2699, in <module>
    worker_setup_crawl(path)
  File "diskover.py", line 1147, in worker_setup_crawl
    start_crawl(path, crawlbot)
  File "diskover.py", line 1083, in start_crawl
    for root, dirs, files in walk(path):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 654, in _walk
    for entry in walk(new_path, topdown, onerror, followlinks):
  File "/home/AD/johnb/diskover-venv/lib/python2.7/site-packages/scandir.py", line 603, in _walk
    entry = next(scandir_it)
  File "/home/AD/johnb/diskover-venv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8a in position 69: invalid start byte
```
I'm guessing there are some filenames with some Latin-1 encoding, or maybe just errant bytes input by a user accidentally.

**Comment by pa-jberanek** [comment] 2018-01-19 11:52
With verbose output I don't see anything obvious which points to the (sort of) file it's tripping up on

**Comment by pa-jberanek** [comment] 2018-01-19 14:15
OK, so a little digging in the directories it was scanning at the time reveals a file:

enior \212\212\212\212\212\206citizens and DC Brandon Kane's ex- \212\212\212\212\212\206wife makes an error of judgement

**Comment by scr512** [comment] 2018-01-30 22:25
I saw something like this when running the crawl script using Python 2.7. Python 3.x worked better.

Posting about this over in the Google Groups page: https://groups.google.com/forum/?hl=en#!topic/diskover/HXNYxkEkP2A

**Comment by shirosaidev** [comment] 2018-06-15 04:07
Duplicate of #21

**Closed** 2018-06-17 02:29 UTC
